### ISSUE TITLE
Gather information for known devices configurations

### ISSUE THREAD

**Issue by Samsagax** [Samsagax/hhfc#1]
Gather info on handhelds to be able to have at least an example for them. Most handhelds are similar but would be nice to have a compendium of sane default configurations for them.

**Comment by Crashdummyy** [comment]
Sample config for the [Aokzoe A1](https://www.kickstarter.com/projects/aokzoeofficial/aokzoe-worlds-first-amd-6800u-powered-game-console).
Requires the installation of [oxp-sensors](https://gitlab.com/Samsagax/oxp-platform-dkms#install)

```yml
SENSORS:
  - name: "cpu"
    driver_name: "k10temp"
    temp_input: "temp1_input"
    divisor: 1000
    offset: 0
  - name: "gpu"
    driver_name: "amdgpu"
    temp_input: "temp1_input"
    divisor: 1000
    offset: 0
FANS:
  - name: "fan1"
    driver_name: "oxpec"
    handle: "pwm1"
    max_control_value: 255
    min_control_value: 0
    fan_input: "fan1_input"
    allow_shutoff: "yes"
    minimum_duty_cycle: 25
    sensors:
      - name: "cpu"
        curve: [
         [40, 0],
         [50, 30],
         [60, 50],
         [70, 100]
        ]
      - name: "gpu"
        curve: [
         [40, 0],
         [50, 30],
         [60, 50],
         [70, 100]
        ]
```
