### ISSUE TITLE
Make lower duty cycle cut-off configurable

### ISSUE THREAD

**Issue by Samsagax** [Samsagax/hhfc#2]
Currently the lower cutoff for the duty cycle of the fan is not configurable. Ideally we should have a lower threshold for the minimum alowed fan duty cycle (for durability reasons) and a flag to be able to completely shut it off.

This could look like:
```yaml
FAN:
  - name: fan
    ...
    allow_shutoff: yes # yes | no
    minimum_duty_cycle: 30 # should be a percentage
```

This could change the behaviour of the lower cutoff. By default it should be not allowed to shutoff and minimum set to 30% for safe values when not set in the configuration.
